# Generated by Django 2.0.4 on 2018-06-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
