# Generated by Django 2.0.4 on 2018-06-20 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building', '0010_auto_20180615_1618'),
        ('building_post', '0003_remove_buildingpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPostHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='building.Building')),
                ('building_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='building_post.BuildingPost')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'building_post_history',
                'ordering': ['-pk'],
            },
        ),
    ]
