# Generated by Django 2.0.4 on 2018-04-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='img_src',
            field=models.ImageField(default=None, upload_to='buildings/'),
        ),
    ]
