# Generated by Django 2.0.4 on 2018-05-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_auto_20180425_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
