# Generated by Django 2.0.4 on 2018-05-24 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building', '0003_building_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'building_post',
                'ordering': ['-updated'],
            },
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='buildingpost',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='building.Building'),
        ),
        migrations.AddField(
            model_name='buildingpost',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
