# Generated by Django 2.0.4 on 2018-05-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_auto_20180524_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingpost',
            name='building',
        ),
        migrations.RemoveField(
            model_name='buildingpost',
            name='creator',
        ),
        migrations.DeleteModel(
            name='BuildingPost',
        ),
    ]
