# Generated by Django 2.0.4 on 2018-06-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_auto_20180524_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
