# Generated by Django 2.0.4 on 2018-06-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_auto_20180608_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='slug',
        ),
    ]
