# Generated by Django 2.0.4 on 2018-06-14 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building', '0008_building_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('img_src', models.ImageField(default=None, upload_to='buildings/')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='building.Building')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Cities')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'building_history',
                'ordering': ['-pk'],
            },
        ),
    ]
