# Generated by Django 2.0.4 on 2018-06-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_buildinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='img_src',
            field=models.ImageField(default=None, null=True, upload_to='buildings/'),
        ),
        migrations.AlterField(
            model_name='buildinghistory',
            name='img_src',
            field=models.ImageField(default=None, null=True, upload_to='buildings/history/'),
        ),
    ]
